### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by JackOfSpade** [oseiskar/black-hole#10]
Infinite loading on Chrome

**Comment by oseiskar** [comment]
What Chrome version and OS does this happen on? What errors are you seeing in the [JavaScript developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)?

**Comment by JackOfSpade** [comment]
Windows 10, latest Chrome.

Console:
![Untitled](https://user-images.githubusercontent.com/3615459/90987433-12e3f200-e559-11ea-889a-deb0778ef797.png)

**Comment by oseiskar** [comment]
I presume it works if you open the official, hosted version at https://oseiskar.github.io/black-hole/

The issue you are facing seems to cloning the repo / copying the files and opening `index.html` from your local filesystem in your browser. That does not work, see this discussion for details: https://stackoverflow.com/questions/50197495/javascript-modules-and-cors/50197517. You have to use a local web server (like `python -m SimpleHttpServer`) to run locally.
